### ISSUE TITLE
Is the latest npm package correct? [v0.3.0]

### ISSUE THREAD

**Issue by rinobatin** [aurelia/testing#10]
I followed example mentioned [here](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/).

The v0.3.0 npm package does not work. `StageComponent` is always undefined.

I tried using the github release and it worked. [Edit 2: I used dist/aurelia-testing.js from this repo]

Can anyone please confirm?

[Edit: I'm using typescript/systemjs/jasmine/karma]

**Comment by EisenbergEffect** [comment]
I'll investigate this. There may be something incorrect in the package config.

**Comment by AStoker** [comment]
Yes, I noticed this, and it's changed in 0.3.0. I had to import `aurelia-testing/component-tester` (as posted to just `aurelia-testing`). The default export for `aurelia-testing` just exports `CompileSpy`, `ViewSpy`, and `configure` (https://github.com/aurelia/testing/blob/master/src/aurelia-testing.js#L11). The component-tester file contains the `StageComponent` function you need.

**Comment by gabor-farkas** [comment]
I also had this problem with ComponentTester, it's not re-exported in '[aurelia-testing](https://github.com/aurelia/testing/blob/master/src/aurelia-testing.js)'. Typescript compilation finds it, but it's not there at runtime.

**Comment by forestmarie** [comment]
Same here - I had to use import {StageComponent} from "aurelia-testing/component-tester";   fyi - I just jspm installed aurelia-testing today...

**Comment by EisenbergEffect** [comment]
We'll get this fixed. Apologies!

**Comment by EisenbergEffect** [comment]
Fixed and released.
