### ISSUE TITLE
Can't resolve ./compile-spy or ./view-spy after 1.1.0 upgrade

### ISSUE THREAD

**Issue by lebolo** [aurelia/testing#101]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
MacOS 12.3.1

* **Node Version:**
15.14.0

* **NPM Version:**
7.7.6

* **JSPM OR Webpack AND Version**
webpack cli 3.3.12 (webpack 4.46.0)

* **Language:**
TypeScript 3.9.7

**Current behavior:**
On running `npm run build:dev` (aliased to `webpack --extractCss --env.NODE_ENV=development`), I get the following build error:

```
ERROR in ./node_modules/aurelia-testing/dist/native-modules/aurelia-testing.js
Module not found: Error: Can't resolve './compile-spy' in '/builds/.../node_modules/aurelia-testing/dist/native-modules'
 @ ./node_modules/aurelia-testing/dist/native-modules/aurelia-testing.js
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-bootstrapper

ERROR in ./node_modules/aurelia-testing/dist/native-modules/aurelia-testing.js
Module not found: Error: Can't resolve './view-spy' in '/builds/.../node_modules/aurelia-testing/dist/native-modules'
 @ ./node_modules/aurelia-testing/dist/native-modules/aurelia-testing.js
 @ ./src/main.ts
 @ ./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js
 @ multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-bootstrapper
```

This is from our build pipeline. If I lock down aurelia-testing in our package-json to ~1.0.0 (it used to be ^1.0.0 and was picking up 1.1.0 on an `npm i`), it works.

**Comment by 3cp** [comment]
https://aurelia.io/blog/2022/5/10/aurelia-updates-for-may-2022/
