### ISSUE TITLE
PhantomJs/Wallabyjs

### ISSUE THREAD

**Issue by yacuzo** [aurelia/testing#19]
Hello,

I had some issues running tests with the new ComponentTester with Wallabyjs.
It looked like some sort of polyfill issue which broke aurelia setup.

The problem existed with Wallaby which by default uses Phantomjs 1.9.8. Following the instructions here: https://wallabyjs.com/docs/integration/phantomjs2.html to setup wallaby with phantomjs 2.1.1 removed the problem.

Given PhantomJs' popularity for testing I would say this issue warrants a note somewhere in the docs.

**Comment by EisenbergEffect** [comment]
@yacuzo Using this link you can submit a PR directly to the component tester docs: https://github.com/aurelia/testing/edit/master/doc/article/en-US/testing-components.md

We would appreciate it if you could use your experience with this issue to add a note there. We'd be happy to merge it.
