### ISSUE TITLE
not binding

### ISSUE THREAD

**Issue by doktordirk** [aurelia/testing#23]
**I'm submitting a bug report**
- **Library Version:**
  aurelia-testing@1.0.0-beta.1.0.3
- **Operating System:**
  Windows 10
- **Node Version:**
  5.70
- **NPM Version:**
  3.6.0
- **JSPM**
  0.16.39
- **Browser:**
  Chrome  51.0.2704.103
- **Language:**
  ESNext

**Current behavior:**
Sample code in the docs doesn't bind 'Bob' and the test fails. (i replaced name with firstName there everywhere as there are still errors in i think

**Expected/desired behavior:**
That 'Bob' is bound and the test works.

**Question/Suggestion:**
Is there a working sample anywhere. Maybe add one to the todo-app

**Comment by EisenbergEffect** [comment]
We've got the docs fixed up under source now. They just haven't been released yet. We'll get a content update out next week at the latest.

**Comment by doktordirk** [comment]
ah,, alright. the sample there worked now

**Comment by TKTheTechie** [comment]
@doktordirk  - sorry, I can't seem to find the fix. Can you post the link?

**Comment by doktordirk** [comment]
check the /doc folder in this repo
