### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by doktordirk** [aurelia/testing#25]
Following works in the app, but with aurelia-testing the element does not get created.  There is no error message.

``` js
import {bindable, BindingEngine} from 'aurelia-framework';
import {inject} from 'aurelia-dependency-injection';

@inject(BindingEngine)
    export class MyComponent {
      @bindable firstName;

      constructor(bindingEngine,) {
      this.bindingEngine  = bindingEngine;
    }
```

maybe related:
function 'processor' does not get called in aurelia-testing:

``` js
import {processContent} from 'aurelia-templating';

function processor(compiler, resources, node, instruction){
  console.log(compiler, resources, node, instruction);
  return true;
}

@processContent(processor)
export class MyAttributeCustomAttribute {
  static inject = [Element];
      constructor(element) {
        this.element = element;
      }

      valueChanged(newValue){
        this.element.style.backgroundColor = newValue;
      }
    }
```

**Comment by EisenbergEffect** [comment]
@martingust Can you take a look?

**Comment by martingust** [comment]
@EisenbergEffect I'm on vacation for another week or so without access to computer. If no one else have looked into this before I get back I will.

**Comment by doktordirk** [comment]
might be the reason https://github.com/aurelia/framework/issues/480

**Comment by tkhyn** [comment]
@doktordirk you may want to try and add a timeout. The quickest way is to replace the `0` at the end of [this line](https://github.com/aurelia/testing/blob/master/src/component-tester.js#L64) by a reasonably high number of milliseconds. Of course you'll have to replace it in the transpiled code, in the jspm package folder for aurelia-testing.

If it works with a timeout, then it's likely to be related.

**Comment by doktordirk** [comment]
re timeout: i played with it, but to no avail. but considering i get component.dispose undefined or something, it still seem related (since it'll get defined within some promise and no-one waited for it to resolve apparently)

**Comment by doktordirk** [comment]
any news?

**Comment by doktordirk** [comment]
hmm, samples i gave above work fine now.
