### ISSUE TITLE
View not rendering when using StageComponent

### ISSUE THREAD

**Issue by skeane50** [aurelia/testing#26]
**I'm submitting a bug report**
- **Library Version:**
  aurelia 1.0.0-rc.1.0.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 7
- **Node Version:**
  6.2.0
  
  
- **NPM Version:**
  3.8.9
  
  
- **JSPM OR Webpack AND Version**
  JSPM 0.16.32 
  
  
- **Browser:**
  Chrome Version 51.0.2704.103 m
- **Language:**
  ESNext

**Current behavior:**
I tried following the tutorial at http://aurelia.io/hub.html#/doc/article/aurelia/testing/latest/testing-components/2 for unit testing custom elements and attributes but the view does not render properly for me and the tests continue to fail. 

This is the error message I receive when running through the first tutorial:

```
Expected '' to be 'Bob'.
```

 I tried to incorporate it into my own project as well abut it only seems to work if I create a variable called viewModel and bind the attributes to that and then assign it to the component.

**Expected/desired behavior:**
How do I go about unit testing the view?

- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**

**Comment by doktordirk** [comment]
see Issue # 23 (not binding) at aurelia/testing
https://github.com/aurelia/testing/issues/23
