### ISSUE TITLE
feature request: waitForElement à la selenium-webdriver

### ISSUE THREAD

**Issue by tkhyn** [aurelia/testing#28]
**I'm submitting a feature request**

As pointed out in aurelia/framework#480, it seems that there is no way to wait for a component to be fully rendered before the start of a test. This led me to think that a waitForElement method (sort of mimicking the one that can be used in selenium) would be a good thing to have in `aurelia-testing`.

**Current behavior:**

When a component (typically a component containing `compose` tags or children custom elements) takes more time to render that it takes to exit the `ComponentTester.create` function, the test may start without having the component rendered in the DOM.

For the moment, the only way to tackle this is to add an adequate timeout before the test starts.

**Expected/desired behavior:**

I would be happy to have a `ComponentTester.waitForElement(getter: () => Element): Promise<void>` that would resolve as soon as the getter returns something else than `null`. Of course it would reject the promise after a pre-set (possibly user-defined) timeout. This method would use polling to check at regular intervals if the element is present or not.

Following the example in the doc, the usage would be as follows:

``` javascript
component.waitForElement(() => document.querySelector('.firstName')).then((nameElement) => {
  expect(nameElement.innerHTML).toBe('Bob');
  done();
});
```

or, a bit prettier with async/await:

``` javascript
await nameElement = component.waitForElement(() =>document.querySelector('.firstName'));
expect(nameElement.innerHTML).toBe('Bob');
done();
```

**Proposed solution**

Below is a very basic version of the method I'm thinking of.

Enhancements could include:
- ability to understand other 'empty' values than `null` (checking the length of a returned jQuery object for example)
- or even better, ability to simply take a selector (XPATH, CSS selector ...) as an argument so that there is no need to worry about a getter function. That would also enable the function to provide a bit more information on what element was not found in the error message.
- timeout and polling interval customization (global and/or for each call)

``` javascript

export class ComponentTester {
  [...]

  waitForElement(getter): Promise<Element> {

    // prevents infinite recursion if the request times out
    var timedOut = false;

    function wait() {
      var element = getter();
      if (element !== null || timedOut) {
        return Promise.resolve(element);
      }
      return new Promise(rs => setTimeout(rs, 200)).then(wait);
    }

    return Promise.race([
      new Promise((rs, rj) => setTimeout(() => {
          timedOut = true;
          rj('Element not found');
        }, 5000)
      ),
      wait()
    ]);
  }


```

How does it sound? I can submit a PR with just that if it's good enough.

**Comment by EisenbergEffect** [comment]
@martingust Any thoughts on this?

**Comment by AStoker** [comment]
@tkhyn, would something like this help? https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

That way you're just listening to the element change events and not firing off timeouts left and right in tests.

**Comment by tkhyn** [comment]
@AStoker 

Yes I thought about using observers but it's not trivial (at all) to implement if the aim is to support different getter functions, especially if the element waited for is nested far deep in the DOM, especially if you want to use jQuery selectors (which I do), etc...

I think that using timeout is the easiest / most reliable / most versatile way to do, and as it's a testing tool I'd say it's ok to fire timeouts (especially as we're expecting just a few timeouts to be fired, not thousands). If I'm not mistaken that's the approach used by selenium webdriver.

**Comment by tkhyn** [comment]
FYI here is the slightly improved version I've been using for a few weeks now. Additionnally supports:
- checking jQuery elements
- checking for absence of element
- custom interval and timeouts

``` javascript

    waitForElement(getter, options): Promise<Element> {

        // prevents infinite recursion if the request times out
        var timedOut = false;

        options = Object.assign({
            present: true,
            interval: 50,
            timeout: 5000
        }, options);


        function wait() {
            var element = getter(),
                // boolean is needed here, hence the length > 0
                found = element !== null && (!element.jquery || element.length > 0);

            if (!options.present^found || timedOut) {
                return Promise.resolve(element);
            }

            return new Promise(rs => setTimeout(rs, options.interval)).then(wait);
        }

        return Promise.race([
            new Promise((rs, rj) => setTimeout(() => {
                    timedOut = true;
                    rj(options.present ? 'Element not found' : 'Element not removed');
                }, options.timeout)
            ),
            wait()
        ]);
    }

```

**Comment by martingust** [comment]
I think this is a great improvement. @tkhyn Feel free to submit a PR.

**Comment by timfish** [comment]
The pull request has been merged but I can't find any of the `waitForElement` methods in any of the `dist` output or TypeScript definitions. Whats left here?

**Comment by EisenbergEffect** [comment]
It needs to be built and released still.
