### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by doktordirk** [aurelia/testing#30]
**I'm submitting a feature request**
- **Library Version:**
  1.0.0-rc1.0.03

**Current behavior:**
there are no tests

**Expected/desired behavior:**
have tests
- **What is the motivation / use case for changing the behavior?**
  tests are good :smile:

**Comment by martingust** [comment]
Done in https://github.com/aurelia/testing/commit/6680ff2fdb8acd78c5a3990c84651306c16a226c, thanks!
