### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by plwalters** [aurelia/testing#35]
# Overview

aurelia-testing is a great library for improving testing lifecycle and associated DOM elements.  Right now the library is in a great place but the documentation makes it a bit difficult to jump in to as some of the information is spread around a bit between hub and the initial blog post, making it difficult to deduce the proper way to test different scenarios and also to understand the "intentions" of the library.  I'm opening this issue to propose some documentation improvements that I would like to chip in on (and anyone else of course)
## Topics under current `Testing Components`
1. Testing Custom Elements
   a. Expand to current to cover testing capabilities
   - manuallyHandleLifeCycle
   - testing viewModel state
   - Using instances of a real parent component for testing (ex. instantiating a `ParentViewModel` and passing as the bound context)
   - using multi-line HTML elements in tests for legibility
2. Testing Custom Attributes
   a. Expand to show using real custom elements as the context
   a. Show how to verify jQuery-style library outputs
3. Testing Value Converters
   a. New docs to show how to use with value converters and when (may not be needed since value converter methods can be tested sans the testing library)
4. Locating resources
   a. Cover how resources are located during test run
   - Show how to debug missing resources
   - Examples of how to add paths in karma to resources
## New topic `General Testing`
1. General Testing
   a. How to test without the aurelia testing library (not always needed, ex. testing services or some resources that are independent of DOM)
   b. General debugging tips (karma, jasmine, etc...)
   c. Testing glossary
   d. General unit testing tips 
   - various obvious tips for unit testing to help newcomers
2. Writing our first Unit Test
   a. Walk through writing a test of a real component from the skeleton

**Comment by EisenbergEffect** [comment]
@PWKad Go for it :)

**Comment by Alaboudi1** [comment]
Any update on this issue?

**Comment by nashwaan** [comment]
Its 2017, any progress here, please?

**Comment by plwalters** [comment]
Yes mostly in docs already
