### ISSUE TITLE
Catch errors from loaders and emit instead of relying on the dev to

### ISSUE THREAD

**Issue by plwalters** [aurelia/testing#38]
Current the developer needs to add a catch to every component is being created if there are issues such as not being able to load a resource.  We should be able to catch those and emit a console error to aid the developer in the workflow.

**Comment by plwalters** [comment]
Note after this is complete need to make sure the docs reflect that `catch` isn't needed

**Comment by EisenbergEffect** [comment]
@PWKad I assigned you :)

**Comment by Alexander-Taran** [comment]
Seems like it is done

**Comment by Alexander-Taran** [comment]
Maybe can be closed

**Comment by EisenbergEffect** [comment]
Looks like we added some docs. Also, I think this will be much improved in vNext as well.
