### ISSUE TITLE
Package  aurelia-validation not supported?

### ISSUE THREAD

**Issue by altenstedt** [aurelia/testing#45]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-beta.2.0.0

* **Operating System:**
Windows 10

* **Node Version:**
4.5.0
* **NPM Version:**
2.15.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.45
* **Browser:**
Chrome 54.0.2840.99 m (64-bit)

* **Language:**
ESNext

**Current behavior:**
Potentially unhandled rejection [1] Error: No BindingBehavior named "validate" was found!

**Expected/desired behavior:**

I have a view that I use the aurelia-validation package, v0.13.1  Bindings are using the "& validate" syntax.  When running tests, I get a an error saying that binding behavior "validate" was not found.

Is it possible to use the aurelia-testing package to test views that use the aurelia-validation package?

**Comment by EisenbergEffect** [comment]
@jdanyow Thoughts?

**Comment by jdanyow** [comment]
The validation library's own test suite uses aurelia-testing to test itself. It should work. Did you call .plugin('aurelia-validation') in your test?

**Comment by EisenbergEffect** [comment]
Seems like a setup issue. Closing for now but we can assist the OP if he has further issues.

**Comment by altenstedt** [comment]
I did _not_ call .plugin() in my tests!  

Thanks also for the pointer to aurelia-validation library's own test suite. That code helped me _a lot_, understanding how to use aurelia-validation for scenarios that are a little more complex than the ones covered in the documenation.
