### ISSUE TITLE
Typescript typing for StageComponent

### ISSUE THREAD

**Issue by llicht** [aurelia/testing#46]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-beta.2.0.0

**Please tell us about your environment:**
* **Language:**
Typescript 2

**Current behavior:**
1) StageComponent is of type any, which means the typings of ComponentTester aren't taken advantage of when StageComponent is used.
2) If you workaround (1), you'll find that doing "component.create (bootstrap)" like the documentation suggests fails typescript's type-check since ComponentTester.create expects a function that takes an Aurelia object while bootstrap is a function that takes a Function.

**Expected/desired behavior:**
It would be better if StageComponent & ComponentTester had full & correct typings under typescript.

**Comment by EisenbergEffect** [comment]
Would you be interested in submitting a PR to fix the types in the code?

**Comment by llicht** [comment]
I'll keep that in mind, but I likely won't be able to.

**Comment by s-hoff** [comment]
@llicht any updates, are you still on to this?

**Comment by llicht** [comment]
No, I'm not working on this currently, feel free to submit the PR.
