### ISSUE TITLE
Testing of two-way bindings in Custom Element

### ISSUE THREAD

**Issue by AStoker** [aurelia/testing#5]
## Help Wanted

I'm trying to test the view of my custom element, but am having some difficulty.  
I'm at the stage of trying to ensure that values entered in the View are being reflected in the View Model. It seems, however, that I cannot get the timing right, since the view model does not update when the view is updated (there are some operations in the task queue I believe that need to happen in order for this to work).  
I've tried using the ui-virtualization techniques for testing (https://github.com/aurelia/ui-virtualization/blob/master/test/virtual-repeat-integration.spec.js#L5), and it seems to work for changes from the view model to the view, but not the other way around.  My basic need is for being able to test changes in the view, so if there is a better way to do this, I'd appreciate hearing it.  

Some of my code: 

``` javascript
function createAssertionQueue() { //https://github.com/aurelia/ui-virtualization/blob/master/test/virtual-repeat-integration.spec.js#L5
  let queue = [];

  let next;
  next = () => {
    if (queue.length) {
      let func = queue.pop();
      setTimeout(() => {
        func();
        next();
      })
    }
  };

  return func => {
    queue.push(func);
    if (queue.length === 1) {
      next();
    }
  };
}
let nq = createAssertionQueue();
...
...
beforeEach(()=>{

        viewModel = {
            queryString: '',
            filter: []
        };
        component = StageComponent
            .withResources('resources/customElements/search-bar/search-bar')
            .inView('<search-bar query.two-way="queryString" filters.bind="filters" ></search-bar')
            .boundTo(viewModel);
    });
...
...
describe('can two way bind the query', () => {
    it('from the viewModel to View', done => {
            component.create()
                .then(() => {
                    const elem = $('search-bar');
                    nq(()=>viewModel.queryString = 'foo');
                    nq(()=>{
                        let val = $(elem).find('.query').val();
                        expect(val).toBe('foo');
                    });
                    nq(()=> done());
                });
   });
   it('from the View to viewModel', done => {
            component.create()
                .then(()=>{
                    const elem = $('search-bar');
                    nq(()=>$(elem).find('.query').val('bar'));
                    nq(()=>{
                        expect(viewModel.queryString).toBe('bar');
                    });
                    nq(()=> done());
                });
        })
    });
```

**Comment by AStoker** [comment]
Might be that I should try and use Aurelia's micro task queue? Seems a bit overkill perhaps, and if not, I'm not sure how I'd get the correct instance of the task queue inside a test.

**Comment by EisenbergEffect** [comment]
@AStoker Have you used the latest release of the testing library? Here's a blog post with some details: http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/

**Comment by AStoker** [comment]
I saw that and was extremely pleased with what was added! However, it didn't seem to cover the case of testing changes in data, which is what I'm trying to test. It seems like it does lifecycle callbacks well, and initial binding well. But the post didn't mention how to test cases of when the data changes live, and I couldn't find much inside the testing repo either regarding this.  
Maybe I'm going down the wrong road for trying to test changes in the UI.

**Comment by EisenbergEffect** [comment]
@martingust What are your thoughts? Is this a missing feature/scenario we should address with the library?

**Comment by EisenbergEffect** [comment]
@jdandyow Feel free to chime in as well.

**Comment by AStoker** [comment]
^^ @jdanyow?

**Comment by martingust** [comment]
@AStoker I have not done any testing from view to viewModel, but I'm surprised it doesn't work, will need to look into that. Does you view update if you print out the value? Like if you use a markup like this:

`.inView('${queryString}<search-bar query.two-way="queryString" filters.bind="filters" ></search-bar>')`

**Comment by AStoker** [comment]
The view doesn't update in that way, no. What does update is one of the input values in the custom element, but that's to be expected since we're updating that with jQuery. Neither the view model, or the binding in the view are updated.

**Comment by jdanyow** [comment]
@AStoker, assuming `.query` is an input element:

``` js
it('from the View to viewModel', done => {
            component.create()
                .then(()=>{
                    const elem = $('search-bar');

                    nq(()=>$(elem).find('.query').val('bar'));   <------ change this
                    nq(()=>$(elem).find('.query').val('bar').trigger('change'));    <------ to something like this
                    nq(()=>{
                        expect(viewModel.queryString).toBe('bar');
                    });
                    nq(()=> done());
                });
        })
    });
```

The binding system is observing input elements by listening for "change" and "input" events.  When you change the value programatically the DOM doesn't fire these events so the binding system doesn't know the input changed.

For folks that aren't using JQuery:

``` js
el.dispatchEvent(DOM.createCustomEvent('change'));
```

https://github.com/aurelia/binding/blob/master/test/checked-observer.spec.js#L56-L63

**Comment by AStoker** [comment]
@jdanyow, unfortunately using jQuery didn't work, triggering the change did nothing to help the queryString change in the view model. 
However, trying your approach of using `aurelia-pal` DOM to create a custom event did seem to work.  
So end result, I have the test passing, but using the jQuery 'change' event doesn't work.  
Not sure if this is due to something special that is being done inside aurelia-pal (I'd love to learn more about what the library does), or if jQuery isn't simulating the change event the right way. In either case, it is probably something to either document or address, since lots of us lazy developers like jQuery :P

**Comment by jdanyow** [comment]
I think it's because JQuery doesn't fire real DOM events.

**Comment by AStoker** [comment]
And the aurelia-pal framework fires real DOM events?

**Comment by AStoker** [comment]
Okay, found the documentation (as much as there is at least) for Aurelia Pal, and think I understand a bit more about it. It would be helpful to have some more documentation about more than just the API's of the repos, but also the purpose behind the functionality (not a topic for here though). 
My problem was that events were not firing in such a way that Aurelia knew that values were changing. Using the DOM functionality in Aurelia-Pal to fire the events worked. So it looks like I should be using the aurelia-pal DOM for most of my testing of DOM objects? 
And since the issue is resolved, I'll go ahead and close the issue. I'm just trying to get some answered cleared up for any future developers running into testing issues.

**Comment by EisenbergEffect** [comment]
There isn't much documentation on that because it's mostly intended for internal use, but I can see more scenarios where it could be used by developers, especially going forward.

It mainly provides a set of helper APIs that serve as a lightweight abstraction over the DOM. It was designed with a forward-looking intent to implement server rendering. The event firing capabilities don't really do anything special but pass through to normal DOM apis under the hood.

**Comment by AStoker** [comment]
Thanks for explaining. Would it be unsafe to use the DOM object off of aurelia-pal?

**Comment by EisenbergEffect** [comment]
Nope. It's safe :)

**Comment by AStoker** [comment]
Awesome, thanks all for the help.
