### ISSUE TITLE
Cannot run asynchronous tests (e.g. ComponentTester#create)

### ISSUE THREAD

**Issue by michaelbull** [aurelia/testing#54]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Library Version:**

`dependencies`:
- aurelia-bootstrapper-webpack@1.1.0
- aurelia-event-aggregator@1.0.1
- aurelia-framework@1.0.8
- aurelia-history-browser@1.0.0
- aurelia-http-client@1.0.4
- aurelia-logging-console@1.0.0
- aurelia-templating-binding@1.2.0
- aurelia-templating-resources@1.2.0
- aurelia-templating-router@1.0.1

`devDependencies`:
- aurelia-bootstrapper@2.0.1
- aurelia-protractor-plugin@1.0.1
- aurelia-template-lint-loader@1.0.1
- aurelia-testing@1.0.0-beta.2.0.1
- aurelia-webpack-plugin@1.0.0-beta.4.0.1

**Please tell us about your environment:**
* **Operating System:**
Linux (debian jessie)

* **Node Version:**
6.9.4

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
webpack 2.2.0

* **Browser:**
Chrome 55.0.2883.87

* **Language:**
TypeScript 2.1.5

**Current behavior:**

I have a test specification as shown below. Since upgrading from webpack 1.x to 2.2.x the Jasmine specification (ran by Karma) no longer runs successfully, instead I get a `TypeError` printed to the console and the test slowly times out after around 5 seconds, claiming that `Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`.

This seems to be an issue with the `done: DoneFn` type, but I've also tried typing it to `any` and it has no effect. It is worth noting that this worked perfectly fine in webpack 1.x. 

What leads me to believe that the  `done: DoneFn` argument is responsible is the situation in which I remove the argument from the test spec along with the `done();` call. Doing so will prevent Karma from printing the `TypeError`, however but the test will **not** run any assertions, i.e. your spec can be `testee.create(bootstrap as any).then(() => { expect(1).toBe(2); });` and it will still pass, thus indicating that the assertion is not actually being evaluated.

```typescript
import { bootstrap } from 'aurelia-bootstrapper';
import { StageComponent, ComponentTester } from 'aurelia-testing';
import { Paginator } from '../../../src/components/paginator';

describe('Paginator', () => {
    let testee: ComponentTester;

    beforeEach(() => {
        let view: string = `
            <paginator  
                current.two-way="page" 
                total.bind="result.pages" 
                range="4">
            </paginator>
        `;

        let data: Object = {
            page: 5,
            result: {
                total: 100,
                pages: 10
            }
        };

        testee = StageComponent
            .withResources('components/paginator')
            .inView(view)
            .boundTo(data);
    });

    afterEach(() => {
        testee.dispose();
    });

    it('should render the current page', (done: DoneFn) => {
        testee.create(bootstrap as any).then(() => {
            expect(currentPage()).toBe(6);
            done();
        });
    });
});

function currentPage(): number {
    return Number(currentButton().textContent);
}

function currentButton(): Element {
    return document.querySelector('.paginator__selector--current') as Element;
}
```

**Expected/desired behavior:**

* **What is the expected behavior?**

This test should run successfully instead of timing out with the following error:

```
ERROR LOG: TypeError{}
ERROR: TypeError{}
ERROR LOG: TypeError{}
ERROR: TypeError{}

  Paginator
    ✗ should render the current page
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

* **What is the motivation / use case for changing the behavior?**

Being able to write unit level tests for custom components.

**Comment by AdamWillden** [comment]
I'm having the same issue, is there a workaround?

**Comment by AdamWillden** [comment]
I should add that I use JSPM not webpack so it's not necessarily webpack related.

**Comment by AdamWillden** [comment]
Hmm. I've uninstalled and reinstalled my dev dependencies (`aurelia-testing` and `aurelia-bootstrap`), fixed up a few tests (which were broken in numerous ways) and now its working. I wonder if the error shown is a result of a broken test/setup. Least it appears so in my case.

Unfortunately I can't be certain exactly what operation fixed it for me.

**Comment by michaelbull** [comment]
@AdamWillden do you have dynamic resolutions for your dependencies (i.e. using a special ^ or ~ character in your `package.json`) for those two dependencies? Would be interesting to know if it fixed itself because you reinstalled with dynamic resolutions and pulled in a newer version of those packages.

**Comment by AdamWillden** [comment]
Hi @michaelbull, I only started with `aurelia-testing` today so the testing and bootstrap dependencies I downloaded would have been the latest. 

I had the aforementioned issue, I then tried an older version of aurelia-testing (back to beta.1.0.0) to no avail, I then fixed my tests and it started working (one example of an issue was that my `.html` files were not being served). I tried updating to 2.0.1 and it was still working. I then reverted all my package npm/jspm dependency changes to revert au-bootstrap and au-testing package installs, reinstalled both and it was still working. FWIW I only did a jspm install for this entire project today so no other dependencies would have been updated either.

I know that doesn't help much, but that's why i'm leaning towards it being a test/setup issue.

If it helps here's some of my test code for a simple component:

```ts
import '../setup'; //this contains import 'aurelia-polyfills' and import 'jasmine-promises'
import { bootstrap } from 'aurelia-bootstrapper';
import { StageComponent, ComponentTester } from 'aurelia-testing';
import { CollapsibleIsland } from '../../src/collapsible-island';

describe('Given the collapsible-island custom element', () => {
  let component: ComponentTester;

  beforeEach(() => {
    component = StageComponent
      .withResources('src/collapsible-island');
  });

  describe('when the view populates neither bindings nor content', () => {
    beforeEach(async () => {
      component = component
        .inView('<collapsible-island></collapsible-island>');
      await component.create(bootstrap as any);
    });

    afterEach(() => {
      component.dispose();
    });

    it('then the header shows placeholder text', () => {
      expect(getHeaderText()).toBe('#header#');
    });

    it('then the content shows placeholder content', () => {
      expect(getContentText()).toBe('#content#');
    });

    it('then the content is not initially visible', () => {
      expect(isContentVisible()).toBe(false);
    });
  });
```

**Comment by AdamWillden** [comment]
@michaelbull scrap that, i just pushed the code to our CI server and it failed with the same issue

```
Chrome 55.0.2883 (Windows 8.1 0.0.0) Featue: An aurelia custom element to toggle the visibility of content beneath a header Given a view which populates neither bindings nor content then the header shows placeholder text FAILED
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

I'll have a look to see what's different about my local setup :-/

**Comment by AdamWillden** [comment]
As I have a working setup, and seemingly a clean repo doesn't work. So I have cloned my working setup to a new directory, run `npm install`, run `gulp test-ci` to confirm the issue persists... except I don't get an issue!

local `npm -v 4.0.5`, `node -v v7.4.0`
server `npm -v 4.1.2`, `node -v v7.5.0`

Looking at your versions i don't think npm/node versions are the issue here. I've downloaded the version from the server complete **with all installed dependencies** to run it locally and again it succeeds.

I've now re-run it on the server and it still fails there. I'm confused.

**Comment by AdamWillden** [comment]
I was also on chrome 55 yesterday (same version as you) yet this morning my PC showed chrome 56. IT must have updated it sometime. Unfortunately I've updated chrome on the CI server to 56 and it's still exhibiting the same issue.

I can't think what else to try.

**Comment by AdamWillden** [comment]
npm, node and global npm dependency versions are now in sync (local vs server) to no avail. 

The only difference I can think of now is that my laptop is windows 10 but the server is windows server 2012, however I saw the issue yesterday on my windows 10 laptop and you are on linux.

**Comment by AdamWillden** [comment]
@niieani the code I gave you on gitter last night for #57 is the same code I'm having issues with here.

**Comment by AdamWillden** [comment]
@michaelbull @niieani stupidly I should have tried this before but I increased the value of `jasmine.DEFAULT_TIMEOUT_INTERVAL` to 10 seconds for the CI server.

```
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 0 of 10 SUCCESS (0 secs / 0 secs)
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 1 of 10 SUCCESS (0 secs / 13.698 secs)
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 2 of 10 SUCCESS (0 secs / 13.722 secs)
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 3 of 10 SUCCESS (0 secs / 13.748 secs)
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 4 of 10 SUCCESS (0 secs / 13.78 secs)
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 5 of 10 SUCCESS (0 secs / 13.808 secs)
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 6 of 10 SUCCESS (0 secs / 13.864 secs)
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 7 of 10 SUCCESS (0 secs / 13.887 secs)
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 8 of 10 SUCCESS (0 secs / 13.925 secs)
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 9 of 10 SUCCESS (0 secs / 13.956 secs)
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 10 of 10 SUCCESS (0 secs / 13.979 secs)
Chrome 56.0.2924 (Windows 8.1 0.0.0): Executed 10 of 10 SUCCESS (18.369 secs / 13.979 secs)
```

Not sure what causes it to take that long though, I think that is the bug here.

**Comment by ajoslin103** [comment]
I am having the same issue with the skeleton-esnext-webpack

html:
```
<template>
	<div class="row text-center">
		<span id="statusL1">${statusLine1}</span>
		<span id="statusL2">${statusLine2}</span>
	</div>
</template>
```
js:
```
import {customElement, bindable} from 'aurelia-framework';
@customElement('pss-messages')
export class PSSMessagesCustomElement {
	@bindable statusLine1 = '';
	@bindable statusLine2 = '';
}
```
spec:
```
import {StageComponent} from 'aurelia-testing';
import {bootstrap} from 'aurelia-bootstrapper';
describe('PSSMessages', () => {
	let component;
	beforeEach(() => {
		component = StageComponent
		.withResources('src/custom/pss-messages')
		.inView('<pss-messages status-line1.bind="status1" status-line2.bind="status2"></pss-messages>')
		.boundTo({ status1: 'Foo', status2: 'Bar' });
	});
	it('should render status 1', async done => {
		try {
			await component.create(bootstrap);
			const nameElement = document.querySelector('#statusL1');
			expect(nameElement.innerHTML).toBe('Foo');
			done();
		} catch (err) {
			console.log('err', err.toString());
		}
	});
	afterEach(() => {
		component.dispose();
	});
});
```
error:
```
✖ 1 test failed
FAILED TESTS:
  PSSMessages
    ✖ should render status 1
      Chrome 58.0.3029 (Mac OS X 10.12.3)
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```
alternate: (then instead of async) -- no difference, same error
```
it('should render status 1', done => {
		component.create(bootstrap).then(() => {
			const nameElement = document.querySelector('#statusL1');
			expect(nameElement.innerHTML).toBe('Foo');
			done();
		}).catch(e => { console.log(e.toString()); });
	});
```
Note: when I move the create to the: beforeEach stanza the error changed to: you can't dispose before you create

**Comment by niieani** [comment]
An example of using Karma/Mocha with `aurelia-testing` landed in master, in the skeleton-navigation repo. If you keep experiencing these problems, please let me know here.
