### ISSUE TITLE
Testing with manually added Container instances

### ISSUE THREAD

**Issue by AStoker** [aurelia/testing#6]
I have 2 instances of an api client that I manually register in the `main.js` of my application (they are essentially the same api, but with a different root for the routing of requests).

``` javascript
    let container = aurelia.container;
    container.registerInstance("XApi", new Api(new HttpClient(), 'route/to/api/x'));
    container.registerInstance("YApi", new Api(new HttpClient(), 'route/to/api/y'));
```

This is all fine and dandy in the application. And in one of my custom elements, during the `created` callback, a request is made to an api class (this api class being called injects those two api clients to make the actual 'get' requests).  
Trouble is, at no point in the test are those instances of the api base's registered with the container. This is obviously a problem, so I figured I'd try to import the Container from the `aurelia-dependency-injection` and register those api instances in the test.  

``` javascript
import {Container} from 'aurelia-dependency-injection';
...
let container = new Container();
    container.registerInstance("XApi", new Api(new HttpClient(), 'route/to/api/x'));
    container.registerInstance("YApi", new Api(new HttpClient(), 'route/to/api/y'));

```

Well, no success there unfortunately either. This is probably due to the fact that the container instances for the test and the one that I made to register the api clients are completely different (I'd image so since I new'd up the container in the test).  
So the question is, is there a path to correctly register classes within tests? And if not, is there a way to access the container used within the test?

**Comment by EisenbergEffect** [comment]
Can you share some of your test code?

**Comment by AStoker** [comment]
The test suite in question:

``` javascript
//etrieve-header.test.js
import {StageComponent} from 'aurelia-testing';
import {Container} from 'aurelia-dependency-injection';
import {HttpClient} from 'aurelia-fetch-client';

import $ from 'jquery';

import {Api} from '../../../api/Api';



describe('EtrieveHeader', () => { 
    let component;
    let viewModel;

    let container = new Container();
    container.registerInstance("FlowApi", new Api(new HttpClient(), 'webapi/api/'));
    container.registerInstance("FormApi", new Api(new HttpClient(), 'forms/api/'));

    beforeEach(()=>{
        viewModel = {
            navigation:  [
                {
                    href: 'foo',
                    title: 'Foo',
                    settings: {
                        group: 'foo',
                        icon: 'test/resources/Leaf'
                    }
                },
                {
                    href: 'bar',
                    title: 'Bar',
                    settings: {
                        group: 'bar',
                        icon: 'test/resources/Chevron'
                    }
                }
            ],
            brand:"Testing"
        };
        component = StageComponent
            .withResources([
                'resources/customElements/etrieve-header/etrieve-header',
                'resources/customElements/etrieve-logo/etrieve-logo',
                'resources/customElements/tab-nav/tab-nav',
                'resources/customElements/svg-inject/svg-inject',
            ])
            .inView('<etrieve-header navigation.bind="navigation" brand.bind="brand"></etrieve-header>')
            .boundTo(viewModel)
    });

    afterEach(() => {
        viewModel = null;
        component.dispose();
    });

    it('can render the component', done => {
        component.create()
            .then(() => {
                const elem = document.querySelector('etrieve-header');
                expect(elem.children.length > 0).toBe(true);
            })
            .then(done);
    });   

});
```

``` javascript
//UserApi.js
import {inject} from 'aurelia-framework';
import UserCache from './UserApi.Cache'

@inject("FlowApi", "FormApi")
export class UserApi{

    constructor(FlowApi, FormApi){
        this.flowApi = FlowApi;
        this.formApi = FormApi;
    }

    get(useCache = false){
        return Promise.all([this.flowApi.get('User/Get', null, useCache), this.formApi.get('User/Get', null, useCache)]) //this.flowApi errors because it is defined here as "FlowApi" instead of the actual api instance. Same with this.formApi
            .then(response => {
                UserCache.CurrentUser = response;
                return response;
            });
    }
}
```

**Comment by AStoker** [comment]
Inside the calling code where the problem is starting is here, inside the custom element being tested

``` javascript
//etrieve-header.js
...
export class EtrieveHeaderCustomElement{
...
   created(){ //Since this is called as a lifecycle callback, it is expecting this.userApi.get to work.
        //get user
        this.userApi.get().then((u)=>{
            this.user = UserCache.CurrentUser;

            if(this.user && (this.user.CanAccessFlow || this.user.CanAccessForms)){
                this.loadEndPoints();
            }

        });
    }
...
}
```

**Comment by EisenbergEffect** [comment]
@martingust Can you instruct @AStoker how to access the container that is used by the component staging framework?

**Comment by AStoker** [comment]
Sorry I have all kinds of questions regarding the testing framework today! Heavy tests are what we used to have before switching to Aurelia, and so we've finally gotten some time to get started on it, and there are just a lot of things that are still unknown (and I also know it's still in development). I appreciate y'alls help.

**Comment by EisenbergEffect** [comment]
No need to apologize. This will help us refine things. I'm fairly certain you can gain access to the container. Martin can clarify. It it's not possible, we can probably add it quickly and get it into a release next week.

**Comment by EisenbergEffect** [comment]
Assuming, the container issue were solved, how do you like the new testing helper?

**Comment by AStoker** [comment]
I'm enjoying it. It makes it real simple to get started. I was pleased that I could start writing tests right out of the box with it, and without any headaches (one of those few times things just worked the first time). We're still diving into it, so I'm sure we'll find some more advanced cases, but right now, I'd give it a thumbs up.

**Comment by AStoker** [comment]
We'll begin testing our other modules of code later this week, and those aren't custom elements, but rather modules that are routed to. It might fall under E2E testing, but we'd like to be able to test each module with it's view individually. Not sure if the testing helper can accomplish that yet, as I imagine there'd be some more in depth setup with dependencies and such.

**Comment by martingust** [comment]
@AStoker To access the container you can override the [configure function](https://github.com/aurelia/testing/blob/master/src/component-tester.js#L22), get hold of the `aurelia` instance and access the container. 

``` javascript
component = StageComponent
            .withResources([
                'resources/customElements/etrieve-header/etrieve-header',
                'resources/customElements/etrieve-logo/etrieve-logo',
                'resources/customElements/tab-nav/tab-nav',
                'resources/customElements/svg-inject/svg-inject',
            ])
            .inView('<etrieve-header navigation.bind="navigation" brand.bind="brand"></etrieve-header>')
            .boundTo(viewModel);

component.configure = aurelia => {
     aurelia.use.standardConfiguration();
     aurelia.container.registerInstance("FlowApi", new Api(new HttpClient(), 'webapi/api/'));
     aurelia.container.registerInstance("FormApi", new Api(new HttpClient(), 'forms/api/'));     
   }
```

**Comment by AStoker** [comment]
Thanks @martingust, that works. Sorry for the late response, had a few other issues I needed to resolve before getting back and making sure this worked.
