### ISSUE TITLE
Feature request: Stubbed ValidationController

### ISSUE THREAD

**Issue by bulldetektor** [aurelia/testing#63]
Unit testing ViewModels with ValidationRules are impossible if you're using WebPack or JSPM (and who isn't?). There's an closed, but IMHO un-resolved, issue for this over in the aurelia-validation repo (https://github.com/aurelia/validation/issues/377), but the only work-around that I've found to work is to disable ValidationRules when unit testing. But the validation of input is one of the core tenants to unit test, and we loose a lot of testability once we start using aurelia-validation.

Therefore; It would be really great if you could make an implementation of the ValidationController that could be used by unit tests and which honors the validation rules one has defined on the view model.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you take a look into this request?

**Comment by jdanyow** [comment]
The unit tests for aurelia-validation use aurelia-testing. You should be able to copy one of them to get started.

https://github.com/aurelia/validation/blob/master/test/validate-binding-behavior.ts

**Comment by bulldetektor** [comment]
@jdanyow Thanks, but I've already tried to use the StageComponent etc. But I haven't got it running with mocha using jspm. Whatever I try I always end up with the _"Did you forget to add ".plugin('aurelia-validation)" to your main.js?"_ error.

What I really want is to unit test my view model without depending on runtime initialization and loading of Aurelia. I want my validation rules to "just work" with as little plumbing and hazzle as possible...

**Comment by sebandres** [comment]
I have the exact same scenario/problem, I am trying to test my view model without having to spin up Aurelia (I just want to call the class itself) and I get the ".plugin('aurelia-validation)" to your main.js?" given validation rules seem to have been built to run only inside of Aurelia.

**Comment by jereckley** [comment]
To reiterate "Unit testing ViewModels with **ValidationRules** are impossible if you're using WebPack or JSPM"... the example link https://github.com/aurelia/validation/blob/master/test/validate-binding-behavior.ts doesn't seem to import **ValidationRules**. Kinda stuck not being able to test vm's/services importing **ValidationRules**. Thanks!

**Comment by jereckley** [comment]
As a quick follow up I got it all working... and quite nicely. It really just needed Aurelia's component testing setup as mentioned and the needed services mocked out. No problem with the ValidationRules anymore and @jdanyow your examples were most helpful and awesome. Thanks!

**Comment by Alexander-Taran** [comment]
Can be closed

**Comment by TimVevida** [comment]
@jereckley I keep struggeling to get aurelia-validation to work properly. In my case, the component test is a little more complicated, using a parent ViewModel which contains the validation which should be picked up in my component.
Anyway, could you post a code sample of your working configuration?

**Comment by jereckley** [comment]
@TimVevida Sorry it took so long to respond... we(or a lot of us) lost power on the east coast for a bit. I also am working on a huge front end application and the tests are complex. I'm not sure posting them would help to much but if there is some way we can work on that together I'd be happy to. Honestly it's still super buggy and we kinda have put it(html state unit tests) on the back burner because the tests run so inconsistently. We are using Jest and it seems each "spin up" test needs its own test file but even then they pass/fail inconsistently. Let me know if you there is any other way I could help/collaborate...

**Comment by TimVevida** [comment]
Ah, it seems you have your own problems. Let me struggle with this a bit more.
