### ISSUE TITLE
Question: Converting from the old way of doing things.

### ISSUE THREAD

**Issue by forestmarie** [aurelia/testing#9]
Given the current setup:

```
describe("Background Company Cards Tests", () => {
    let cardsViewModel,
        templatingEngine,
        container;

    beforeEach(function() {
        container = new Container();
        container.registerInstance(Element, {});
        templatingEngine = container.get(TemplatingEngine);
        cardsViewModel = templatingEngine.createViewModelForUnitTest(Cards);
    });

    it("calls sets lastFilter to the filters passed in", () => {
            let response = { pageCount: 0, totalItemCount: 0, items: [] };
            spyOn(cardsViewModel.service, "getAll").and.returnValue(Promise.resolve(response));

            let filter = { "foo": "bar"};
            cardsViewModel.load(filter);

            expect(cardsViewModel.lastFilter).toBe(filter);
        });
```

How does this get converted to the newer model?  

The blog that Rob did only covered a few cases mostly around the lifecycle not calling methods of the component itself.  Please let me know.

**Comment by EisenbergEffect** [comment]
@martingust Can you explain the usage? Also, we need to get a doc in place on this. If you can put together something in markdown, we can use this for the docs site article on unit testing.

**Comment by martingust** [comment]
@forestmarie In its simplest form it would convert something like this 

##### View `cards.html`

``` javascript
<template>
  <h1>Cards</h1>
</template>
```

##### ViewModel `cards.js`

``` javascript
export class Cards {
  load(filter) {
    this.lastFilter = filter;
  }
}
```

##### Test `cards.spec.js`

``` javascript
import {StageComponent} from 'aurelia-testing';

describe('Background Company Cards Tests', () => {
  it('calls sets lastFilter to the filters passed in', done => {
     const component = StageComponent.withResources('src/cards').inView('<cards></cards>');
     component.create().then(() => {
         let filter = { "foo": "bar"};
         component.viewModel.load(filter);
         expect(component.viewModel.lastFilter).toBe(filter);
         done();
     });
  });
});
```

**Comment by martingust** [comment]
@EisenbergEffect For sure!

**Comment by forestmarie** [comment]
@martingust Do you know if this should work with the wallaby starter skeleton?  I'm getting undefined on StateComponent

```
import './setup';
//import Promise from 'bluebird';
import {StageComponent} from 'aurelia-testing';
import {Welcome} from '../../src/welcome';

describe('MyComponent', () => {
  it('can render the component', done => {
    let a = StageComponent;
    const component = StageComponent.withResources('src/welcome').inView('<welcome></welcome>');
    console.log(component);
    component.create().then(() => {
         let result = component.viewModel.fullName();
         expect(result).toBe("foo");
         done();
    }).catch(error => {
       fail(error);
       done();
     });
    });
  });
```

In my case, a is undefined.  I'm not very used to webpack yet, but I play with it after hours.  Let me know if this just a webpack issue.  I'll try in our jspm project tomorrow.

**Comment by martingust** [comment]
@forestmarie No webpack support yet, here is an issue tracking that https://github.com/aurelia/testing/issues/4

**Comment by forestmarie** [comment]
@martingust thanks for  answering. From a guidance perspective, do you see the component tester being used to test view model behaviors or would you recommend just newing those up and passing in stubs as done in the starter?  The component tester really seems focused on reusable components. 

Thanks.

**Comment by martingust** [comment]
Yes, what you said. All the none Aurelia stuff I would test outside of Aurelia, just standard unit testing.
