### ISSUE TITLE
Jest aurelia-router mock breaks StageComponent

### ISSUE THREAD

**Issue by michaelw85** [aurelia/testing#90]
**I'm submitting a bug report**

* **Library Version:**
"aurelia-testing": "^1.0.0"

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
v10.15.1

* **NPM Version:**
6.4.1

* **Webpack**
"webpack": "^4.27.0",

* **Browser:**
N/A

* **Language:**
TypeScript 3.3.1

**Current behavior:**
Error occurs when using `StageComponent` in combination with a aurelia-router mock.

```js
Cannot find module '<ROOT>\test\unit\aurelia-templating-router' from 'aurelia-loader-nodejs.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at advancedRequire (node_modules/aurelia-loader-nodejs/dist/commonjs/aurelia-loader-nodejs.js:72:28)
      at NodeJsLoader.<anonymous> (node_modules/aurelia-loader-nodejs/dist/commonjs/aurelia-loader-nodejs.js:192:46)
      at step (node_modules/aurelia-loader-nodejs/dist/commonjs/aurelia-loader-nodejs.js:37:23)
      at Object.next (node_modules/aurelia-loader-nodejs/dist/commonjs/aurelia-loader-nodejs.js:18:53)
```

**Steps to reproduce**
1) Create a new project using latest cli, choose custom and select a TS+Jest setup
2) Create folder `__mocks__` in the root of the project
3) Add empty file `aurelia-router.ts`
4) Replace app.spec.ts with the following test:
```js
import { ComponentTester, StageComponent } from 'aurelia-testing';
import { bootstrap } from 'aurelia-bootstrapper';

describe('this', () => { 
  it('will throw an error', async () => {
      const component: ComponentTester = StageComponent.withResources('app').inView('<app></app>');
      await component.create(bootstrap);
  });
});
```
5) run tests  `au jest`

To successfully run the "test" rename the aurelia-router.ts to anything else and rerun.

**Expected/desired behavior:**
I should be able to use StageComponent and have a aurelia-router mock in place. This mock file should not affect this test unless I specifically want to use the mock.

**Comment by zewa666** [comment]
But isn't the approach with mocking a dependency via the __mocks__ folder that they are [automatically loaded](https://jestjs.io/docs/en/manual-mocks#mocking-node-modules). In that case it would make sense since the mock file is empty and thus leading to an error since nothing is exported

**Comment by michaelw85** [comment]
@zewa666 Thanks for the info, I was under the impression mock are not automatically loaded since [automock](https://jestjs.io/docs/en/configuration#automock-boolean) is false by default. Reading the documentation you are linking states differently for node modules. This gives me some new insight and I will have another look. 

P.S I also had a complete mock with content and it also failed so I figured it was not related.

**Comment by michaelw85** [comment]
@zewa666 This documentation pointed me into the right direction!

To get StageComponent (quickly) working again I added:
`jest.unmock('aurelia-router');`

The jest docs really confused me I was not expecting automatic mocks which made me think something went wrong in the StageComponent module.

**Comment by zewa666** [comment]
Yeah Jest docs are massive but somewhat hard to digest. Anyway Im glad you found the issue

**Comment by michaelw85** [comment]
Thanks allot for your help this resolved multiple issues (seemingly unrelated) I was struggling with. I finished a PR to the jest docs today adding a note to the automock setting.
